package org.apache.ibatis.mybatis测试.mapper;

import java.util.List;
import org.apache.ibatis.mybatis测试.entity.UserInfoEntity;

public interface UserInfoEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 15 14:47:53 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 15 14:47:53 CST 2023
     */
    int insert(UserInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 15 14:47:53 CST 2023
     */
    UserInfoEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 15 14:47:53 CST 2023
     */
    List<UserInfoEntity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Wed Mar 15 14:47:53 CST 2023
     */
    int updateByPrimaryKey(UserInfoEntity record);
}